/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuizzesImport } from './routes/quizzes'
import { Route as AttemptsImport } from './routes/attempts'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as QuizQuizIdImport } from './routes/quiz.$quizId'
import { Route as QuizQuizIdIndexImport } from './routes/quiz.$quizId.index'
import { Route as QuizQuizIdAttemptAttemptIdImport } from './routes/quiz.$quizId.attempt.$attemptId'
import { Route as QuizQuizIdAttemptAttemptIdIndexImport } from './routes/quiz.$quizId.attempt.$attemptId.index'
import { Route as QuizQuizIdAttemptAttemptIdSummaryImport } from './routes/quiz.$quizId.attempt.$attemptId.summary'

// Create/Update Routes

const QuizzesRoute = QuizzesImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRoute,
} as any)

const AttemptsRoute = AttemptsImport.update({
  id: '/attempts',
  path: '/attempts',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuizQuizIdRoute = QuizQuizIdImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRoute,
} as any)

const QuizQuizIdIndexRoute = QuizQuizIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizQuizIdRoute,
} as any)

const QuizQuizIdAttemptAttemptIdRoute = QuizQuizIdAttemptAttemptIdImport.update(
  {
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => QuizQuizIdRoute,
  } as any,
)

const QuizQuizIdAttemptAttemptIdIndexRoute =
  QuizQuizIdAttemptAttemptIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => QuizQuizIdAttemptAttemptIdRoute,
  } as any)

const QuizQuizIdAttemptAttemptIdSummaryRoute =
  QuizQuizIdAttemptAttemptIdSummaryImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => QuizQuizIdAttemptAttemptIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/attempts': {
      id: '/attempts'
      path: '/attempts'
      fullPath: '/attempts'
      preLoaderRoute: typeof AttemptsImport
      parentRoute: typeof rootRoute
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesImport
      parentRoute: typeof rootRoute
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdImport
      parentRoute: typeof rootRoute
    }
    '/quiz/$quizId/': {
      id: '/quiz/$quizId/'
      path: '/'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof QuizQuizIdIndexImport
      parentRoute: typeof QuizQuizIdImport
    }
    '/quiz/$quizId/attempt/$attemptId': {
      id: '/quiz/$quizId/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/quiz/$quizId/attempt/$attemptId'
      preLoaderRoute: typeof QuizQuizIdAttemptAttemptIdImport
      parentRoute: typeof QuizQuizIdImport
    }
    '/quiz/$quizId/attempt/$attemptId/summary': {
      id: '/quiz/$quizId/attempt/$attemptId/summary'
      path: '/summary'
      fullPath: '/quiz/$quizId/attempt/$attemptId/summary'
      preLoaderRoute: typeof QuizQuizIdAttemptAttemptIdSummaryImport
      parentRoute: typeof QuizQuizIdAttemptAttemptIdImport
    }
    '/quiz/$quizId/attempt/$attemptId/': {
      id: '/quiz/$quizId/attempt/$attemptId/'
      path: '/'
      fullPath: '/quiz/$quizId/attempt/$attemptId/'
      preLoaderRoute: typeof QuizQuizIdAttemptAttemptIdIndexImport
      parentRoute: typeof QuizQuizIdAttemptAttemptIdImport
    }
  }
}

// Create and export the route tree

interface QuizQuizIdAttemptAttemptIdRouteChildren {
  QuizQuizIdAttemptAttemptIdSummaryRoute: typeof QuizQuizIdAttemptAttemptIdSummaryRoute
  QuizQuizIdAttemptAttemptIdIndexRoute: typeof QuizQuizIdAttemptAttemptIdIndexRoute
}

const QuizQuizIdAttemptAttemptIdRouteChildren: QuizQuizIdAttemptAttemptIdRouteChildren =
  {
    QuizQuizIdAttemptAttemptIdSummaryRoute:
      QuizQuizIdAttemptAttemptIdSummaryRoute,
    QuizQuizIdAttemptAttemptIdIndexRoute: QuizQuizIdAttemptAttemptIdIndexRoute,
  }

const QuizQuizIdAttemptAttemptIdRouteWithChildren =
  QuizQuizIdAttemptAttemptIdRoute._addFileChildren(
    QuizQuizIdAttemptAttemptIdRouteChildren,
  )

interface QuizQuizIdRouteChildren {
  QuizQuizIdIndexRoute: typeof QuizQuizIdIndexRoute
  QuizQuizIdAttemptAttemptIdRoute: typeof QuizQuizIdAttemptAttemptIdRouteWithChildren
}

const QuizQuizIdRouteChildren: QuizQuizIdRouteChildren = {
  QuizQuizIdIndexRoute: QuizQuizIdIndexRoute,
  QuizQuizIdAttemptAttemptIdRoute: QuizQuizIdAttemptAttemptIdRouteWithChildren,
}

const QuizQuizIdRouteWithChildren = QuizQuizIdRoute._addFileChildren(
  QuizQuizIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attempts': typeof AttemptsRoute
  '/quizzes': typeof QuizzesRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
  '/quiz/$quizId/attempt/$attemptId': typeof QuizQuizIdAttemptAttemptIdRouteWithChildren
  '/quiz/$quizId/attempt/$attemptId/summary': typeof QuizQuizIdAttemptAttemptIdSummaryRoute
  '/quiz/$quizId/attempt/$attemptId/': typeof QuizQuizIdAttemptAttemptIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attempts': typeof AttemptsRoute
  '/quizzes': typeof QuizzesRoute
  '/quiz/$quizId': typeof QuizQuizIdIndexRoute
  '/quiz/$quizId/attempt/$attemptId/summary': typeof QuizQuizIdAttemptAttemptIdSummaryRoute
  '/quiz/$quizId/attempt/$attemptId': typeof QuizQuizIdAttemptAttemptIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attempts': typeof AttemptsRoute
  '/quizzes': typeof QuizzesRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
  '/quiz/$quizId/attempt/$attemptId': typeof QuizQuizIdAttemptAttemptIdRouteWithChildren
  '/quiz/$quizId/attempt/$attemptId/summary': typeof QuizQuizIdAttemptAttemptIdSummaryRoute
  '/quiz/$quizId/attempt/$attemptId/': typeof QuizQuizIdAttemptAttemptIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attempts'
    | '/quizzes'
    | '/quiz/$quizId'
    | '/quiz/$quizId/'
    | '/quiz/$quizId/attempt/$attemptId'
    | '/quiz/$quizId/attempt/$attemptId/summary'
    | '/quiz/$quizId/attempt/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attempts'
    | '/quizzes'
    | '/quiz/$quizId'
    | '/quiz/$quizId/attempt/$attemptId/summary'
    | '/quiz/$quizId/attempt/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attempts'
    | '/quizzes'
    | '/quiz/$quizId'
    | '/quiz/$quizId/'
    | '/quiz/$quizId/attempt/$attemptId'
    | '/quiz/$quizId/attempt/$attemptId/summary'
    | '/quiz/$quizId/attempt/$attemptId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttemptsRoute: typeof AttemptsRoute
  QuizzesRoute: typeof QuizzesRoute
  QuizQuizIdRoute: typeof QuizQuizIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttemptsRoute: AttemptsRoute,
  QuizzesRoute: QuizzesRoute,
  QuizQuizIdRoute: QuizQuizIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/attempts",
        "/quizzes",
        "/quiz/$quizId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/attempts": {
      "filePath": "attempts.tsx"
    },
    "/quizzes": {
      "filePath": "quizzes.tsx"
    },
    "/quiz/$quizId": {
      "filePath": "quiz.$quizId.tsx",
      "children": [
        "/quiz/$quizId/",
        "/quiz/$quizId/attempt/$attemptId"
      ]
    },
    "/quiz/$quizId/": {
      "filePath": "quiz.$quizId.index.tsx",
      "parent": "/quiz/$quizId"
    },
    "/quiz/$quizId/attempt/$attemptId": {
      "filePath": "quiz.$quizId.attempt.$attemptId.tsx",
      "parent": "/quiz/$quizId",
      "children": [
        "/quiz/$quizId/attempt/$attemptId/summary",
        "/quiz/$quizId/attempt/$attemptId/"
      ]
    },
    "/quiz/$quizId/attempt/$attemptId/summary": {
      "filePath": "quiz.$quizId.attempt.$attemptId.summary.tsx",
      "parent": "/quiz/$quizId/attempt/$attemptId"
    },
    "/quiz/$quizId/attempt/$attemptId/": {
      "filePath": "quiz.$quizId.attempt.$attemptId.index.tsx",
      "parent": "/quiz/$quizId/attempt/$attemptId"
    }
  }
}
ROUTE_MANIFEST_END */
